name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: my-env

    - name: Conda environment creation
      run: conda env create -f environment.yml

    - name: Activate Conda environment
      shell: bash -l {0}
      run: conda activate my-env

    - name: Run pytest
      shell: bash -l {0}
      run: pytest
